BOARD_WIDTH = 10
BOARD_HEIGHT = 10

START_GAME = 1
QUIT_GAME = 2
CONTINUE_PLAY_YES = 3
CONTINUE_PLAY_NO = 4

SPACE_SIZE = 50

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

X_DISTANCE = int((WINDOW_WIDTH - BOARD_WIDTH * SPACE_SIZE) / 2)

Y_DISTANCE = int((WINDOW_HEIGHT - BOARD_HEIGHT * SPACE_SIZE) / 3)

RED = 'red'
YELLOW = 'yellow'
HUMAN = 'human'
COMPUTER = 'computer'

INT_MIN_VALUE = -1

